package generator;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PenseBem {
	
	private static final String SAMPLE = "dbaadcbdaadcbbcbdddbdababdacaccbdababdacaccbdbbcdcdddacaabcaabadbbbcdcdddaccbadbadbbddccbadbadbbdcccbadbabbdabbdabdabccddccddaacdbbddbbcdcbbbdabdddcdcbaadcbdaadcbbcddddbdababdacaccbdababdacaccbddbcdcdddacaabcaabadbbbcdcdddacabadbadbbddccbadbadbbdcccbadbadbdabbdabdabccddccddaacdbbddbbddcbbbdabdddcdcbaadcbdaadcbbcddddbdababdacaccbdababdacaccbdddcdcdddacaabcaabadbbbcdcdddacaaadbadbbddccbadbadbbdcccbadbadbdabbdabdabccddccddaacdbbddbbdacbbbdabdddcdcbbadcbdaadcbbcddbdbdababdacaccbdababdacaccbdddbdcdddacaabcaabadbbbcdcdddacaabdbadbbddccbadbadbbdcccbadbadbbabbdabdabccddccddaacdbbddbbdabbbbdabdddcdcbbbdcbdaadcbbcddbabdababdacaccbdababdacaccbdddbdcdddacaabcaabadbbbcdcdddacaabcbadbbddccbadbadbbdcccbadbadbbdbbdabdabccddccddaacdbbddbbdabdbbdabdddcdcbbbacbdaadcbbcddbaadababdacaccbdababdacaccbdddbdadddacaabcaabadbbbcdcdddacaabcaadbbddccbadbadbbdcccbadbadbbdcbdabdabccddccddaacdbbddbbdabdabdabdddcdcbbbacbdaadcbbcddbaadababdacaccbdababdacaccbdddbdabddacaabcaabadbbbcdcdddacaabcaadbbddccbadbadbbdcccbadbadbbdcadabdabccddccddaacdbbddbbdabdabdabdddcdcbbbacadaadcbbcddbaadcbabdacaccbdababdacaccbdddbdabadacaabcaabadbbbcdcdddacaabcaabbbddccbadbadbbdcccbadbadbbdcaaabdabccddccddaacdbbddbbdabdabcabdddcdcbbbacadaadcbbcddbaadcbabdacaccbdababdacaccbdddbdababacaabcaabadbbbcdcdddacaabcaababddccbadbadbbdcccbadbadbbdcaadbdabccddccddaacdbbddbbdabdabccbdddcdcbbbacaddadcbbcddbaadcbdbdacaccbdababdacaccbdddbdababdcaabcaabadbbbcdcdddacaabcaabadddccbadbadbbdcccbadbadbbdcaadadabccddccddaacdbbddbbdabdabccadddcdcbbbacaddddcbbcddbaadcbdadacaccbdababdacaccbdddbdababdaaabcaabadbbbcdcdddacaabcaabadbdccbadbadbbdcccbadbadbbdcaadadabccddccddaacdbbddbbdabdabccabddcdcbbbacadddccbbcddbaadcbdaaacaccbdababdacaccbdddbdababdacabcaabadbbbcdcdddacaabcaabadbbccbadbadbbdcccbadbadbbdcaadadbbccddccddaacdbbddbbdabdabccabcdcdcbbbacadddcdbbcddbaadcbdaadcaccbdababdacaccbdddbdababdacabcaabadbbbcdcdddacaabcaabadbbbcbadbadbbdcccbadbadbbdcaadadbaccddccddaacdbbddbbdabdabccabcccdcbbbacadddcdcbcddbaadcbdaadcaccbdababdacaccbdddbdababdacaccaabadbbbcdcdddacaabcaabadbbbcbadbadbbdcccbadbadbbdcaadadbadcddccddaacdbbddbbdabdabccabccddcbbbacadddcdcacddbaadcbdaadcbccbdababdacaccbdddbdababdacaccaabadbbbcdcdddacaabcaabadbbbcdadbadbbdcccbadbadbbdcaadadbadbddccddaacdbbddbbdabdabccabccddcbbbacadddcdcabddbaadcbdaadcbbcbdababdacaccbdddbdababdacaccbabadbbbcdcdddacaabcaabadbbbcdcdbadbbdcccbadbadbbdcaadadbadbbdccddaacdbbddbbdabdabccabccddabbbacadddcdcabadbaadcbdaadcbbcbdababdacaccbdddbdababdacaccbdbadbbbcdcdddacaabcaabadbbbcdcdbadbbdcccbadbadbbdcaadadbadbbdccddaacdbbddbbdabdabccabccddaabbacadddcdcabaabaadcbdaadcbbcddababdacaccbdddbdababdacaccbddadbbbcdcdddacaabcaabadbbbcdcddadbbdcccbadbadbbdcaadadbadbbdccddaacdbbddbbdabdabccabccddaacbacadddcdcabaacaadcbdaadcbbcddababdacaccbdddbdababdacaccbddddbbbcdcdddacaabcaabadbbbcdcddddbbdcccbadbadbbdcaadadbadbbdcaddaacdbbddbbdabdabccabccddaacdacadddcdcabaacaadcbdaadcbbcddbbabdacaccbdddbdababdacaccbdddbbbbcdcdddacaabcaabadbbbcdcdddabbdcccbadbadbbdcaadadbadbbdcaadaacdbbddbbdabdabccabccddaacdbcadddcdcabaacaddcbdaadcbbcddbaabdacaccbdddbdababdacaccbdddbdbbcdcdddacaabcaabadbbbcdcdddacbdcccbadbadbbdcaadadbadbbdcaadaacdbbddbbdabdabccabccddaacdbaadddcdcabaacaddcbdaadcbbcddbaabdacaccbdddbdababdacaccbdddbddbcdcdddacaabcaabadbbbcdcdddacadcccbadbadbbdcaadadbadbbdcaaddacdbbddbbdabdabccabccddaacdbacdddcdcabaacadddbdaadcbbcddbaaddacaccbdddbdababdacaccbdddbddacdcdddacaabcaabadbbbcdcdddacaacccbadbadbbdcaadadbadbbdcaaddccdbbddbbdabdabccabccddaacdbacdddcdcabaacadddbdaadcbbcddbaadcacaccbdddbdababdacaccbdddbddacdcdddacaabcaabadbbbcdcdddacaabccbadbadbbdcaadadbadbbdcaaddcbdbbddbbdabdabccabccddaacdbacdbdcdcabaacadddbbaadcbbcddbaadcbcaccbdddbdababdacaccbdddbddacacdddacaabcaabadbbbcdcdddacaabccbadbadbbdcaadadbadbbdcaaddcbabbddbbdabdabccabccddaacdbacdbbcdcabaacadddbbdadcbbcddbaadcbdaccbdddbdababdacaccbdddbddacacdddacaabcaabadbbbcdcdddacaabcabadbadbbdcaadadbadbbdcaaddcbadbddbbdabdabccabccddaacdbacdbbddcabaacadddbbdadcbbcddbaadcbdaccbdddbdababdacaccbdddbddacaccddacaabcaabadbbbcdcdddacaabcaaadbadbbdcaadadbadbbdcaaddcbadbddbbdabdabccabccddaacdbacdbbdacabaacadddbbdabcbbcddbaadcbdaacbdddbdababdacaccbdddbddacaccbdacaabcaabadbbbcdcdddacaabcaabdbadbbdcaadadbadbbdcaaddcbadbbdbbdabdabccabccddaacdbacdbbdababaacadddbbdababbcddbaadcbdaadbdddbdababdacaccbdddbddacaccbdacaabcaabadbbbcdcdddacaabcaababadbbdcaadadbadbbdcaaddcbadbbdbbdabdabccabccddaacdbacdbbdabdbaacadddbbdabaabcddbaadcbdaadcdddbdababdacaccbdddbddacaccbddcaabcaabadbbbcdcdddacaabcaabadadbbdcaadadbadbbdcaaddcbadbbdcbdabdabccabccddaacdbacdbbdabdaaacadddbbdabaaccddbaadcbdaadcbddbdababdacaccbdddbddacaccbdddaabcaabadbbbcdcdddacaabcaabadbdbbdcaadadbadbbdcaaddcbadbbdcadabdabccabccddaacdbacdbbdabdabacadddbbdabaacaddbaadcbdaadcbbdbdababdacaccbdddbddacaccbdddbabcaabadbbbcdcdddacaabcaabadbbbbdcaadadbadbbdcaaddcbadbbdcaaabdabccabccddaacdbacdbbdabdabbcadddbbdabaacaddbaadcbdaadcbbcbdababdacaccbdddbddacaccbdddbdbcaabadbbbcdcdddacaabcaabadbbbbdcaadadbadbbdcaaddcbadbbdcaadbdabccabccddaacdbacdbbdabdabbdadddbbdabaacadcbaadcbdaadcbbcddababdacaccbdddbddacaccbdddbdacaabadbbbcdcdddacaabcaabadbbbcdcaadadbadbbdcaaddcbadbbdcaadddabccabccddaacdbacdbbdabdabbdadddbbdabaacadcbaadcbdaadcbbcddababdacaccbdddbddacaccbdddbdabaabadbbbcdcdddacaabcaabadbbbcdcaadadbadbbdcaaddcbadbbdcaaddcabccabccddaacdbacdbbdabdabbdabddbbdabaacadcbbadcbdaadcbbcddbbabdacaccbdddbddacaccbdddbdabaabadbbbcdcdddacaabcaabadbbbcdcaadadbadbbdcaaddcbadbbdcaaddccbccabccddaacdbacdbbdabdabbdabcdbbdabaacadcbbbdcbdaadcbbcddbaabdacaccbdddbddacaccbdddbdababbadbbbcdcdddacaabcaabadbbbcdcdadadbadbbdcaaddcbadbbdcaaddccbccabccddaacdbacdbbdabdabbdabccbbdabaacadcbbbdcbdaadcbbcddbaabdacaccbdddbddacaccbdddbdababdadbbbcdcdddacaabcaabadbbbcdcdddadbadbbdcaaddcbadbbdcaaddccbdcabccddaacdbacdbbdabdabbdabccdbdabaacadcbbbdabdaadcbbcddbaaddacaccbdddbddacaccbdddbdababdadbbbcdcdddacaabcaabadbbbcdcdddadbadbbdcaaddcbadbbdcaaddccbdbabccddaacdbacdbbdabdabbdabccdddabaacadcbbbdabdaadcbbcddbaadcacaccbdddbddacaccbdddbdababdacbbbcdcdddacaabcaabadbbbcdcdddadbadbbdcaaddcbadbbdcaaddccbdbbbccddaacdbacdbbdabdabbdabccddaabaacadcbbbdabaaadcbbcddbaadcbcaccbdddbddacaccbdddbdababdacabbcdcdddacaabcaabadbbbcdcdddacbadbbdcaaddcbadbbdcaaddccbdbbdccddaacdbacdbbdabdabbdabccddaabaacadcbbbdabadadcbbcddbaadcbdaccbdddbddacaccbdddbdababdacacbcdcdddacaabcaabadbbbcdcdddacaadbbdcaaddcbadbbdcaaddccbdbbdccddaacdbacdbbdabdabbdabccddaacaacadcbbbdabadddcbbcddbaadcbdaccbdddbddacaccbdddbdababdacacccdcdddacaabcaabadbbbcdcdddacaadbbdcaaddcbadbbdcaaddccbdbbdcaddaacdbacdbbdabdabbdabccddaacdacadcbbbdabaddccbbcddbaadcbdaacbdddbddacaccbdddbdababdacaccbdcdddacaabcaabadbbbcdcdddacaabbbdcaaddcbadbbdcaaddccbdbbdcaadaacdbacdbbdabdabbdabccddaacdacadcbbbdabaddcdbbcddbaadcbdaadbdddbddacaccbdddbdababdacaccbdcdddacaabcaabadbbbcdcdddacaabcbdcaaddcbadbbdcaaddccbdbbdcaadaacdbacdbbdabdabbdabccddaacdaaadcbbbdabaddcdcbcddbaadcbdaadcdddbddacaccbdddbdababdacaccbdddddacaabcaabadbbbcdcdddacaabcadcaaddcbadbbdcaaddccbdbbdcaaddacdbacdbbdabdabbdabccddaacdaacdcbbbdabaddcdcbcddbaadcbdaadcbddbddacaccbdddbdababdacaccbdddddacaabcaabadbbbcdcdddacaabcaacaaddcbadbbdcaaddccbdbbdcaaddccdbacdbbdabdabbdabccddaacdaacdcbbbdabaddcdcbbddbaadcbdaadcbbdbddacaccbdddbdababdacaccbdddbdacaabcaabadbbbcdcdddacaabcaabaaddcbadbbdcaaddccbdbbdcaaddccdbacdbbdabdabbdabccddaacdaacdbbbbdabaddcdcbbbdbaadcbdaadcbbcbddacaccbdddbdababdacaccbdddbdacaabcaabadbbbcdcdddacaabcaabaaddcbadbbdcaaddccbdbbdcaaddccbbacdbbdabdabbdabccddaacdaacdbbbbdabaddcdcbbbdbaadcbdaadcbbcdddacaccbdddbdababdacaccbdddbdacaabcaabadbbbcdcdddacaabcaabadddcbadbbdcaaddccbdbbdcaaddccbaacdbbdabdabbdabccddaacdaacdbbdbdabaddcdcbbbdcaadcbdaadcbbcdddacaccbdddbdababdacaccbdddbdabaabcaabadbbbcdcdddacaabcaabadbdcbadbbdcaaddccbdbbdcaaddccbadcdbbdabdabbdabccddaacdaacdbbdadabaddcdcbbbdcaadcbdaadcbbcddbacaccbdddbdababdacaccbdddbdabaabcaabadbbbcdcdddacaabcaabadbbcbadbbdcaaddccbdbbdcaaddccbadbdbbdabdabbdabccddaacdaacdbbdababaddcdcbbbdcaddcbdaadcbbcddbacaccbdddbdababdacaccbdddbdababbcaabadbbbcdcdddacaabcaabadbbbbadbbdcaaddccbdbbdcaaddccbadbdbbdabdabbdabccddaacdaacdbbdabdbaddcdcbbbdcaddcbdaadcbbcddbaaaccbdddbdababdacaccbdddbdababdcaabadbbbcdcdddacaabcaabadbbbcadbbdcaaddccbdbbdcaaddccbadbdcbdabdabbdabccddaacdaacdbbdabddaddcdcbbbdcadddbdaadcbbcddbaadccbdddbdababdacaccbdddbdababdcaabadbbbcdcdddacaabcaabadbbbcddbbdcaaddccbdbbdcaaddccbadbdcadabdabbdabccddaacdaacdbbdabddaddcdcbbbdcadddcdaadcbbcddbaadccbdddbdababdacaccbdddbdababdcbabadbbbcdcdddacaabcaabadbbbcdcbbdcaaddccbdbbdcaaddccbadbdcaaabdabbdabccddaacdaacdbbdabddabdcdcbbbdcadddcdaadcbbcddbaadcbbdddbdababdacaccbdddbdababdcbdbadbbbcdcdddacaabcaabadbbbcdcdbdcaaddccbdbbdcaaddccbadbdcaadbdabbdabccddaacdaacdbbdabddabdcdcbbbdcadddcdcadcbbcddbaadcbddddbdababdacaccbdddbdababdcbddadbbbcdcdddacaabcaabadbbbcdcdddcaaddccbdbbdcaaddccbadbdcaadddabbdabccddaacdaacdbbdabddabdadcbbbdcadddcdcbdcbbcddbaadcbdaddbdababdacaccbdddbdababdcbddddbbbcdcdddacaabcaabadbbbcdcdddcaaddccbdbbdcaaddccbadbdcaaddcabbdabccddaacdaacdbbdabddabdabcbbbdcadddcdcbbcbbcddbaadcbdaadbdababdacaccbdddbdababdcbdddbbbbcdcdddacaabcaabadbbbcdcdddaaaddccbdbbdcaaddccbadbdcaaddccbbdabccddaacdaacdbbdabddabdabcbbbdcadddcdcbbabbcddbaadcbdaadbdababdacaccbdddbdababdcbdddbdbbcdcdddacaabcaabadbbbcdcdddacaddccbdbbdcaaddccbadbdcaaddccbbdabccddaacdaacdbbdabddabdabccbbdcadddcdcbbaabcddbaadcbdaadcdababdacaccbdddbdababdcbdddbdabcdcdddacaabcaabadbbbcdcdddacaddccbdbbdcaaddccbadbdcaaddccbadabccddaacdaacdbbdabddabdabccdbdcadddcdcbbaaccddbaadcbdaadcbababdacaccbdddbdababdcbdddbdabcdcdddacaabcaabadbbbcdcdddacaadccbdbbdcaaddccbadbdcaaddccbadabccddaacdaacdbbdabddabdabccdddcadddcdcbbaacaddbaadcbdaadcbbbabdacaccbdddbdababdcbdddbdabadcdddacaabcaabadbbbcdcdddacaabccbdbbdcaaddccbadbdcaaddccbadbbccddaacdaacdbbdabddabdabccddacadddcdcbbaacaddbaadcbdaadcbbcabdacaccbdddbdababdcbdddbdababcdddacaabcaabadbbbcdcdddacaabccbdbbdcaaddccbadbdcaaddccbadbaccddaacdaacdbbdabddabdabccddacadddcdcbbaacaddbaadcbdaadcbbcdbdacaccbdddbdababdcbdddbdababddddacaabcaabadbbbcdcdddacaabcabdbbdcaaddccbadbdcaaddccbadbadcddaacdaacdbbdabddabdabccddacddddcdcbbaacadddaadcbdaadcbbcdddacaccbdddbdababdcbdddbdababdaddacaabcaabadbbbcdcdddacaabcaadbbdcaaddccbadbdcaaddccbadbadaddaacdaacdbbdabddabdabccddacddddcdcbbaacadddcadcbdaadcbbcddbacaccbdddbdababdcbdddbdababdacdacaabcaabadbbbcdcdddacaabcaabbbdcaaddccbadbdcaaddccbadbadaadaacdaacdbbdabddabdabccddacddadcdcbbaacadddcddcbdaadcbbcddbacaccbdddbdababdcbdddbdababdacaacaabcaabadbbbcdcdddacaabcaababdcaaddccbadbdcaaddccbadbadaadaacdaacdbbdabddabdabccddacddaacdcbbaacadddcddcbdaadcbbcddbaaaccbdddbdababdcbdddbdababdacaccaabcaabadbbbcdcdddacaabcaabaddcaaddccbadbdcaaddccbadbadaaddacdaacdbbdabddabdabccddacddaacdcbbaacadddcddabdaadcbbcddbaadccbdddbdababdcbdddbdababdacaccaabcaabadbbbcdcdddacaabcaabadbcaaddccbadbdcaaddccbadbadaaddccdaacdbbdabddabdabccddacddaacdcbbaacadddcddabdaadcbbcddbaadccbdddbdababdcbdddbdababdacaccbabcaabadbbbcdcdddacaabcaabadbbaaddccbadbdcaaddccbadbadaaddccdaacdbbdabddabdabccddacddaacdbbbaacadddcddabaaadcbbcddbaadcbbdddbdababdcbdddbdababdacaccbdbcaabadbbbcdcdddacaabcaabadbbbaddccbadbdcaaddccbadbadaaddccbaacdbbdabddabdabccddacddaacdbbbaacadddcddabaaadcbbcddbaadcbddddbdababdcbdddbdababdacaccbddcaabadbbbcdcdddacaabcaabadbbbcddccbadbdcaaddccbadbadaaddccbaacdbbdabddabdabccddacddaacdbbdaacadddcddabaacdcbbcddbaadcbdaddbdababdcbdddbdababdacaccbdddaabadbbbcdcdddacaabcaabadbbbcddccbadbdcaaddccbadbadaaddccbadcdbbdabddabdabccddacddaacdbbdaacadddcddabaacacbbcddbaadcbdaadbdababdcbdddbdababdacaccbdddbabadbbbcdcdddacaabcaabadbbbcdcccbadbdcaaddccbadbadaaddccbadbdbbdabddabdabccddacddaacdbbdabcadddcddabaacadbbcddbaadcbdaadbdababdcbdddbdababdacaccbdddbdbadbbbcdcdddacaabcaabadbbbcdcdcbadbdcaaddccbadbadaaddccbadbabbdabddabdabccddacddaacdbbdabbadddcddabaacaddbcddbaadcbdaadcdababdcbdddbdababdacaccbdddbdaadbbbcdcdddacaabcaabadbbbcdcddbadbdcaaddccbadbadaaddccbadbadbdabddabdabccddacddaacdbbdabbddddcddabaacaddbcddbaadcbdaadcbababdcbdddbdababdacaccbdddbdabdbbbcdcdddacaabcaabadbbbcdcdddadbdcaaddccbadbadaaddccbadbadbdabddabdabccddacddaacdbbdabbdaddcddabaacaddbbddbaadcbdaadcbbbabdcbdddbdababdacaccbdddbdababbbcdcdddacaabcaabadbbbcdcdddadbdcaaddccbadbadaaddccbadbadbbabddabdabccddacddaacdbbdabbdabdcddabaacaddbbbdbaadcbdaadcbbcabdcbdddbdababdacaccbdddbdababbbcdcdddacaabcaabadbbbcdcdddacbdcaaddccbadbadaaddccbadbadbbdbddabdabccddacddaacdbbdabbdabdcddabaacaddbbbdbaadcbdaadcbbcdbdcbdddbdababdacaccbdddbdababdbcdcdddacaabcaabadbbbcdcdddacadcaaddccbadbadaaddccbadbadbbddddabdabccddacddaacdbbdabbdabdaddabaacaddbbbdaaadcbdaadcbbcdddcbdddbdababdacaccbdddbdababdacdcdddacaabcaabadbbbcdcdddacaacaaddccbadbadaaddccbadbadbbddcdabdabccddacddaacdbbdabbdabdabdabaacaddbbbdabadcbdaadcbbcddbcbdddbdababdacaccbdddbdababdacdcdddacaabcaabadbbbcdcdddacaabaaddccbadbadaaddccbadbadbbddccabdabccddacddaacdbbdabbdabdabcabaacaddbbbdabadcbdaadcbbcddbcbdddbdababdacaccbdddbdababdacacdddacaabcaabadbbbcdcdddacaabcaddccbadbadaaddccbadbadbbddccbbdabccddacddaacdbbdabbdabdabccbaacaddbbbdabaacbdaadcbbcddbcddddbdababdacaccbdddbdababdacacdddacaabcaabadbbbcdcdddacaabcaddccbadbadaaddccbadbadbbddccbadabccddacddaacdbbdabbdabdabccdaacaddbbbdabaacbdaadcbbcddbcddddbdababdacaccbdddbdababdacaccddacaabcaabadbbbcdcdddacaabcaadccbadbadaaddccbadbadbbddccbadabccddacddaacdbbdabbdabdabccddacaddbbbdabaaccdaadcbbcddbcddbdbdababdacaccbdddbdababdacaccbdacaabcaabadbbbcdcdddacaabcaabccbadbadaaddccbadbadbbddccbadbbccddacddaacdbbdabbdabdabccddccaddbbbdabaaccdaadcbbcddbcddbabdababdacaccbdddbdababdacaccbdacaabcaabadbbbcdcdddacaabcaabacbadbadaaddccbadbadbbddccbadbaccddacddaacdbbdabbdabdabccddccaddbbbdabaaccdcadcbbcddbcddbaadababdacaccbdddbdababdacaccbdacaabcaabadbbbcdcdddacaabcaabadbadbadaaddccbadbadbbddccbadbadcddacddaacdbbdabbdabdabccddccdddbbbdabaaccdcbdcbbcddbcddbaadababdacaccbdddbdababdacaccbdabaabcaabadbbbcdcdddacaabcaabadbadbadaaddccbadbadbbddccbadbadbddacddaacdbbdabbdabdabccddccdddbbbdabaaccdcbbcbbcddbcddbaadcbabdacaccbdddbdababdacaccbdabaabcaabadbbbcdcdddacaabcaabadbbdbadaaddccbadbadbbddccbadbadbbdacddaacdbbdabbdabdabccddccddabbbdabaaccdcbbbbbcddbcddbaadcbabdacaccbdddbdababdacaccbdababbcaabadbbbcdcdddacaabcaabadbbbbadaaddccbadbadbbddccbadbadbbdacddaacdbbdabbdabdabccddccddaabbdabaaccdcbbbdbcddbcddbaadcbdbdacaccbdddbdababdacaccbdababdcaabadbbbcdcdddacaabcaabadbbbcadaaddccbadbadbbddccbadbadbbdccddaacdbbdabbdabdabccddccddaacbdabaaccdcbbbdacddbcddbaadcbdadacaccbdddbdababdacaccbdababdaaabadbbbcdcdddacaabcaabadbbbcddaaddccbadbadbbddccbadbadbbdccddaacdbbdabbdabdabccddccddaacddabaaccdcbbbdabddbcddbaadcbdaaacaccbdddbdababdacaccbdababdacabadbbbcdcdddacaabcaabadbbbcdcaaddccbadbadbbddccbadbadbbdcccdaacdbbdabbdabdabccddccddaacdbabaaccdcbbbdabddbcddbaadcbdaadcaccbdddbdababdacaccbdababdacabadbbbcdcdddacaabcaabadbbbcdcdaddccbadbadbbddccbadbadbbdcccbaacdbbdabbdabdabccddccddaacdbbbaaccdcbbbdabddbcddbaadcbdaadcaccbdddbdababdacaccbdababdacacadbbbcdcdddacaabcaabadbbbcdcddddccbadbadbbddccbadbadbbdcccbaacdbbdabbdabdabccddccddaacdbbdaaccdcbbbdabdddcddbaadcbdaadcbccbdddbdababdacaccbdababdacaccdbbbcdcdddacaabcaabadbbbcdcddddccbadbadbbddccbadbadbbdcccbadcdbbdabbdabdabccddccddaacdbbddaccdcbbbdabdddcdd";

	static ArrayList<ArrayList<Character>> answers = new ArrayList<>();


	public static void main(String[] args) throws FileNotFoundException {
		//precalc();
		readSample();		
	}
	
	
	public static void precalc() {
		
		//esse bloco cria a lista dos livros que por sua vez terá 150 perguntas cada
		for (int b = 0; b < 2; b++){//99; b++) {
			answers.add(new ArrayList<>());
		}

		//essas 150 letras repesentam as repostas corretas que serão trocadas a cada ciclo 
		String pattern1 = "dbaadcbdaadcbbc" + "bdddbdababdacac" + "cbdababdacaccbd" + "bbcdcdddacaabca"
				+ "abadbbbcdcdddac" + "cbadbadbbddccba" + "dbadbbdcccbadba" + "bbdabbdabdabccd" + "dccddaacdbbddbb"
				+ "cdcbbbdabdddcdc";

		String pattern2 = "22221202301023123110332032313302" + "03022121320233203323333220221221"
				+ "30303330010113102300312222030031" + "22201303322312111332102302332023"
				+ "12033033201101201022100330112212" + "31101032132131211313212111330313"
				+ "23120203032010023131303302312120" + "03233301131332001130130102322321"
				+ "00101020113320201200223033300200" + "20332303233320232301303322112030"
				+ "33000131223323032222211303211222" + "01022012130321201023122111120300"
				+ "31213021320123211301301322230130" + "22030130333312012220221103001133"
				+ "10031131131230212010110223103300" + "32322123132020333001212020032303"
				+ "10302221221023033011310303012012" + "12012031321213323020123321303210" + "013020120331";

		for (int b = 0; b < 2; b++){//99; b++) {
			//Esse bloco serve para montar o primeiro livro da pilha que não tem nenhuma alteração em cima do pattern1 que ja existe
			if (b == 0) {
				for (int q = 0; q < 150; q++) {
					answers.get(0).add(pattern1.charAt(q));
				}
				// quando o primeiro livro termina ele pula para o proximo ciclo e nunca mas volta para esse bloco inicial
				continue;
			}

			char first = pattern1.charAt(0);
			for (int q = 0; q < 150; q++) {
				int v = 0;
				if (q % 30 == 14 || q == 149) {
					v = Integer.parseInt(String.valueOf(pattern2.charAt(0)));
					pattern2 = pattern2.substring(1);
				}

				char prev;
				if (q == 149) {
					prev = first;
				} else {
					prev = pattern1.charAt(q + 1);
				}

				pattern1 = pattern1.substring(0, q) + (char) ('a' + (prev - 'a' + v) % 4) + pattern1.substring(q + 1);
			}

			for (int q = 0; q < 150; q++) {
				answers.get(b).add(pattern1.charAt(q));
			}
		}

		System.out.println(answers);
	}

	private static void readSample() throws FileNotFoundException {
		//try {
			//BufferedReader reader = new BufferedReader(new FileReader("C:\\Users\\deibsonemagali\\eclipse-workspace\\teste\\src\\SAMPLES"));
			List<Character> samples = new ArrayList<>();

			//int character;
			//while ((character = reader.read()) != -1) {
			for (char character : SAMPLE.toCharArray()) {
				samples.add((char) character);
			}

			Map<Integer, Character> m = new HashMap<>();
			// int index = 0;
			for (int book = 1; book <= 99; book++) {
				for (int question = 1; question <= 150; question++) {
					char a = samples.remove(0);
					//char a = SAMPLE.charAt(q-1);
					m.put(book * 1000 + question, a);
					//if(book == 1) {
						System.out.println(String.format("%02d", book)+getSession(question) +"--"+ String.format("%03d", question) + "--" + a);
					//}
				}
			}

			//reader.close();

			// Use the 'm' map as needed
			//System.out.println(m);
		//} catch (IOException e) {
		//	e.printStackTrace();
		//}
	}
	
	
	private static String getSession(int question) {
		if (question <= 30) {
			return "1";
		} else if (question >= 31 && question <= 60) {
			return "2";
		} else if (question >= 61 && question <= 90) {
			return "3";
		} else if (question >= 91 && question <= 120) {
			return "4";
		} else if (question >= 121) {
			return "5";
		} else {
			return "";
		}
	}


}
